		<script type="text/javascript" src="http://code.jquery.com/jquery.js"></script>
		<script type="text/javascript" src="/js_fw/jquery.scrollTo-1.4.3.1-min.js"></script>
		<script src="http://code.jquery.com/jquery.js"></script>
		<script src="/js_fw/jquery.validate-1.11.0.min.js"></script>
		<script src="/js_fw/jquery.validate.additional-methods.min.js"></script>
		<script src="/js_fw/bootstrap.min.js"></script>